name: trigger event
run-name: reto trigger

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches: [ "main", "master"]

  issues:
    types:
      - pinned
jobs:

  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run Go
        run: go run main.go
     
